package org.universaltranslator.core;

/** Cheap offline checks used to avoid unnecessary network requests. */
public final class LanguageHeuristics {
    private LanguageHeuristics() {
    }

    public static boolean shouldTranslate(String text, String targetLanguage) {
        if (text == null || text.trim().isEmpty()) {
            return false;
        }
        // Messages generated by the mod itself are already localized and must remain stable.
        if (text.contains("[MC Auto Translation Tool]")
                || text.contains("[MC 自动翻译工具]")
                || text.contains("[Universal Translator]")) {
            return false;
        }
        if (TranslationOutputValidator.containsInternalArtifact(text)) {
            return false;
        }

        int letters = 0;
        int han = 0;
        int japaneseKana = 0;
        int koreanHangul = 0;
        for (int i = 0; i < text.length(); i++) {
            char value = text.charAt(i);
            if (Character.isLetter(value)) {
                letters++;
                Character.UnicodeBlock block = Character.UnicodeBlock.of(value);
                if (block == Character.UnicodeBlock.CJK_UNIFIED_IDEOGRAPHS
                        || block == Character.UnicodeBlock.CJK_COMPATIBILITY_IDEOGRAPHS) {
                    han++;
                }
                if (block == Character.UnicodeBlock.HIRAGANA
                        || block == Character.UnicodeBlock.KATAKANA
                        || block == Character.UnicodeBlock.KATAKANA_PHONETIC_EXTENSIONS) {
                    japaneseKana++;
                }
                if (block == Character.UnicodeBlock.HANGUL_SYLLABLES
                        || block == Character.UnicodeBlock.HANGUL_JAMO
                        || block == Character.UnicodeBlock.HANGUL_COMPATIBILITY_JAMO) {
                    koreanHangul++;
                }
            }
        }

        if (letters == 0) {
            return false;
        }
        // Mixed Chinese/Latin labels still need their Latin portion translated. Existing Han
        // runs are protected later, so skip only when every detected letter is already Han.
        if (isChineseTarget(targetLanguage) && han == letters) {
            return false;
        }
        if (isJapaneseTarget(targetLanguage) && (han + japaneseKana) == letters) {
            return false;
        }
        if (isKoreanTarget(targetLanguage) && koreanHangul == letters) {
            return false;
        }
        return true;
    }

    private static boolean isChineseTarget(String language) {
        if (language == null) {
            return false;
        }
        String normalized = language.toLowerCase().replace('_', '-');
        return normalized.equals("zh") || normalized.startsWith("zh-");
    }

    private static boolean isJapaneseTarget(String language) {
        if (language == null) {
            return false;
        }
        String normalized = language.toLowerCase().replace('_', '-');
        return normalized.equals("ja") || normalized.startsWith("ja-");
    }

    private static boolean isKoreanTarget(String language) {
        if (language == null) {
            return false;
        }
        String normalized = language.toLowerCase().replace('_', '-');
        return normalized.equals("ko") || normalized.startsWith("ko-");
    }
}
